stages:
- build
- cleanup_build

build_job:
  stage: build
  script:
  - git submodule update --init
  - ./gradlew assembleGrinRelease
  - ./gradlew app:dependencies > app/build/outputs/build-dependencies.txt
  - cd app/ziptool/
  - ./build_apk_grin.sh
  artifacts:
    paths:
    - app/build/outputs/apk/*
    - app/build/outputs/mapping/*/release/mapping.txt
    - app/build/outputs/build-dependencies.txt
    expire_in: 1 week
  only:
    - develop_grin
  tags:
  - camera

cleanup_build_job:
  stage: cleanup_build
  script:
  - ./gradlew clean
  when: on_failure

