libCommons:
  RemoteConfig:
    PlistFile: "Local.kb"
    PlistUrl: "http://cdn.appcloudbox.net/keyboardarts/apps/colorkeyboard/configs/config-colorkeyboard-2.4.0.kb"
  Analytics:
      FlurryKey: "GTJN395TKWN6T8T6YKC3"
      FacebookID: "910238615719294"
      TapjoySDKKey: "Y5_zVkZeSreG2Z7B_wtM8gECBliMafnGOk44En6LHlqRPGoWow2uhWFacJZj"
      TapjoyEngagementID: "d407ac82-6255-47e8-9004-295d79998ad4"
      FlyerKey: "d4VKN2yBPk7gqTRBZcwkbc"
      GoogleTrackId: "UA-64233211-2"
      FlurryStoredMaxCount: 1000
      GooglePercentage: 1000
  DiverseSession:
    AppManageDiverseSession: true
  ImageCache:
    CacheSize: 0

  Market:
    DefaultMarket: "Google"
    3rdChannel: "GP"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
      Amazon:
        AppPackage: "com.amazon.venezia"
        AppUrl: "amzn://apps/android?p="
        WebUrl: "http://www.amazon.com/gp/mas/dl/android?p="
  Connection:
    SigKey: "603_3"
    HashKey: "u)};]_4&ydQ4?`|!f?nziKZ/ho_L`on{"
  AppID: "603"
libFramework:
  Push:
    SenderID: "587335381558"
    SendTokenToServer: yes
  Alerts:
    LocalFile: "Alerts.kb"
    RemoteUrl: "http://cdn.appcloudbox.net/keyboardarts/apps/colorkeyboard/alerts/colorkeyboard-2.4.0-alerts.kb"

libIAP:
  Verify:
    ByServer:
      AppID: "603"
      Url: "https://karainbow.appcloudbox.net/keyboard/rainbow/receipt/verify"

libKeyboard:
  DictionaryUrl: "http://cdn.emoji.mobi/googlekeyboard/4.0/"

Application:
  WallpaperAPIURL: "https://service.appcloudbox.net/wallpapers/"