libCommons:
  RemoteConfig:
    PlistFile: "Local.kb"
    PlistUrl: "https://emojidevelop.s3.amazonaws.com/apps_android/config/config-colorkeyboard-2.3.8.kb"
  Analytics:
      FlurryKey: "GTJN395TKWN6XXXXXXXX"
      FacebookID: "910238615719294"
      TapjoySDKKey: "Y5_zVkZeSreG2Z7B_wtM8gECBliMafnGOk44En6LHlqRPGoWow2uhWFacJZj"
      TapjoyEngagementID: "d407ac82-6255-47e8-9004-295d79998ad4"
      FlyerKey: "d4VKN2yBPk7gqTRBZcwkbc"
      GoogleTrackId: "UA-66666666-2"
      FlurryStoredMaxCount: 1000
      GooglePercentage: 1000
  DiverseSession:
    AppManageDiverseSession: true
  ImageCache:
    CacheSize: 0


  Market:
    DefaultMarket: "Google"
    3rdChannel: "GP"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
      Amazon:
        AppPackage: "com.amazon.venezia"
        AppUrl: "amzn://apps/android?p="
        WebUrl: "http://www.amazon.com/gp/mas/dl/android?p="
  Connection:
    SigKey: "603_2"
    HashKey: "x5UJ~fb}3_Dma>l B]YB/?'1As[\"E<I!"
libFramework:
  Push:
    SenderID: ""
    SendTokenToServer: yes
  Alerts:
    LocalFile: "Alerts.kb"
    RemoteUrl: "http://emojidevelop.s3.amazonaws.com/apps_android/alerts/colorkeyboard-2.3.8-alerts.kb"

libIAP:
  Verify:
    ByServer:
      AppID: "603"
      Url: "https://dev-keyboard.appcloudbox.net:7443/keyboard/rainbowkey/receipt/verify"

libKeyboard:
  DictionaryUrl: "http://emojidevelop.s3.amazonaws.com/AndroidResource/languages/"