libCommons:
  RemoteConfig:
    UpdateInterval: 10
    PlistFile: "Local.ic"
    PlistUrl: "https://emojidevelop.s3.amazonaws.com/apps_android/config/config-emojikeyboard-2.1.1.ic"
  Analytics:
      FlurryKey: "FC2GWXDVFTZHFK7KX6KV"
      FacebookID: "1474873346171463"
      TapjoySDKKey: "xngEmwWtQly0k_AqtdONawECiQlH0ihPQFWD0LYIPuBwFQqH1SU3JkosT66A"
      FlyerKey: "d4VKN2yBPk7gqTRBZcwkbc"
      GoogleTrackId: "UA-64233211-2"
  DiverseSession:
    AppManageDiverseSession: true
  ImageCache:
    CacheSize: 0

  Market:
    DefaultMarket: "Google"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
      Amazon:
        AppPackage: "com.amazon.venezia"
        AppUrl: "amzn://apps/android?p="
        WebUrl: "http://www.amazon.com/gp/mas/dl/android?p="
  Connection:
    SigKey: "1"
    HashKey: "x5UJ~fb}3_Dma>l B]YB/?'1As[\"E<I!"
  AppId: "610"

libFramework:
  Push:
    SenderID: "805407701758"
    SendTokenToServer: yes
  Alerts:
    LocalFile: "Alerts.ic"
    RemoteUrl: "http://emojidevelop.s3.amazonaws.com/apps_android/alerts/emojikeyboard-2.1.0-alerts.ic"
      
libKeyboard:
  DictionaryUrl: "http://cdn.emoji.mobi/googlekeyboard/4.0/"

Application:
  WallpaperAPIURL: "https://dev-service.appcloudbox.net/wallpapers/"

adAdapter:
  admobNative:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化
  admobBanner:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化
  admobInterstitial:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化
  adxNative:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化
  adxBanner:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化
  adxInterstitial:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化
  openxBanner:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化
  ironsourceInterstitial:
    initsdkwhenstart : false     //false表示在 load广告时进行SDK的初始化，true表示在App启动时进行初始化，如果没有配置默认是在App启动时进行SDK初始化