libCommons:
  RemoteConfig:
    PlistFile: "Local.mp"
    PlistUrl: "http://cdn.appcloudbox.net/keyboardarts/apps/grinkeyboard/configs/config-grinkeyboard-1.0.0.mp"
  Analytics:
      FlurryKey: "ZK5M56Q5KH3X6PQ9HCT8"
      FacebookID: "617619995295351"
      FlyerKey: "d4VKN2yBPk7gqTRBZcwkbc"
      GoogleTrackId: ""
      FlurryStoredMaxCount: 1000
      GooglePercentage: 1000
  DiverseSession:
    AppManageDiverseSession: true
  ImageCache:
    CacheSize: 0

  Market:
    DefaultMarket: "Google"
    3rdChannel: "GP"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
      Amazon:
        AppPackage: "com.amazon.venezia"
        AppUrl: "amzn://apps/android?p="
        WebUrl: "http://www.amazon.com/gp/mas/dl/android?p="

  Connection:
      SigKey: "612_1"
      HashKey: "R3bG+XlIKb1DZ$sC`k]<5COn-[A}{$4e"
  AppID: "612"
libFramework:
  Alerts:
    LocalFile: "Alerts.mp"
    RemoteUrl: "http://cdn.appcloudbox.net/keyboardarts/apps/grinkeyboard/alerts/grinkeyboard-1.0.0-alerts.mp"

libKeyboard:
  DictionaryUrl: "http://cdn.emoji.mobi/googlekeyboard/4.0/"

Application:
  WallpaperAPIURL: "https://service.appcloudbox.net/wallpapers/"