libCommons:
  RemoteConfig:
    UpdateInterval: 10
    PlistFile: "Local.mp"
    PlistUrl: "xxhttp://cdn.appcloudbox.net/keyboardarts/apps/grinkeyboard/configs/config-grinkeyboard-1.1.4.mp"
  Analytics:
      FlurryKey: "VFHX539WKM27R8ZZ5398"
      FacebookID: "2017803811838675"
      FlyerKey: "d4VKN2yBPk7gqTRBZcwkbc"
      GoogleTrackId: "UA-66468004-2"
  DiverseSession:
    AppManageDiverseSession: true
  ImageCache:
    CacheSize: 0

  Market:
    DefaultMarket: "Google"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
      Amazon:
        AppPackage: "com.amazon.venezia"
        AppUrl: "amzn://apps/android?p="
        WebUrl: "http://www.amazon.com/gp/mas/dl/android?p="
  Connection:
      SigKey: "1"
      HashKey: "x5UJ~fb}3_Dma>l B]YB/?'1As[\"E<I!"
  AppID: "612"

libFramework:
  Push:
    SenderID: "495163548406"
    SendTokenToServer: yes
  Alerts:
    LocalFile: "Alerts.mp"
    RemoteUrl: "http://cdn.appcloudbox.net/keyboardarts/apps/grinkeyboard/alerts/grinkeyboard-1.1.4-alerts.mp"
      
libKeyboard:
  DictionaryUrl: "http://cdn.emoji.mobi/googlekeyboard/4.0/"

Application:
  WallpaperAPIURL: "https://dev-service.appcloudbox.net/wallpapers/"